### ISSUE TITLE
Aligned the Dutch translation, however not visible

### ISSUE THREAD

**Issue by Cpt-xx** [progit/progit2-nl#10]
Hi, I've (finally) aligned the Dutch translation to the 2.1.75 version of the English master version. I've removed most of the referral issues reported by the mobi builder (some of them are really strange, everything seems to be pointing correctly).

However on https://git-scm.com/book/nl/v2 this newer version is not visible. 

Is there something else I need to do besides merging to master? Or is there something you, Ben or Jean-Noel needs to trigger?

**Comment by jnavila** [comment]
Hi @Cpt-xx ,

First, if you want to bring somebody in the conversation, please use @ mention with the user's alias (See https://help.github.com/articles/basic-writing-and-formatting-syntax/#mentioning-people-and-teams)

Second, you have sync'd with the english progit version for the book content, but also for the build chain for PDFs and ebooks. Unfortunately, progit/progit2 does not use the same build system as all the translations. I'll have to roll back to the previous state. The [build log](https://travis-ci.org/progit/progit2-nl) is full of warnings that'll need to be sorted out.

As for the update on git-scm, the scripts are run once a day. Just be patient :watch:   !

**Comment by Cpt-xx** [comment]
Hi @jnavila,

My apologies for not following the conventions.
This not using the same build system is a bit worrying, especially as the translators don't know which build system can/should be used nor how they need to configure them.
IMHO this should be at least the area of the writers of the original document (i.e. progit/progit2, would that be you or @schacon or @ben ?). This is because the translators should not touch any of the tags, hooks, etc. in the document that are used to configure the more technical parts of the document (ToC, index). An exception could be the hooks for the Index, because it looks weird when the document is in, say, Japanese but the index is English only.

I wasn't aware of the git-scm script running once a day. I'll practice my patience :wink:

**Comment by Cpt-xx** [comment]
Hi @jnavila,
There is another thing that strikes me now: the table of contents on git-scm for the Dutch translation doesn't reach farther than chapter 7. However I see that the update hasn't still run (yet? succesfully?) so this might be corrected later today.

**Comment by jnavila** [comment]
Hi @Cpt-xx 

I don't think translators should worry about the build system, which they usually don't fiddle with. From the original writers of the book, only Ben is still active; I guess Scott is too busy elsewhere nowadays. We could align the build tools if ben agrees, but it really doesn't matter in the end

For the content of the book, I had to make some changes to the way cross links are managed, but did not port it completely identical in English, afterwards. Please note that this issue only concerns internal cross-links, and it is quite easy to check the compilation result to assert that they were not broken. It is a pain to debug because the errors usually don't point on the origin of the issues (asciidoctor is to permissive with regards to document structure), but at least you can tell when your patch broke the book.

Index entries, ToC and other book content can and should be translated. It's up to the translator to educate themselves on asciidoctor and understand the formatting and what needs to be translated.

For the content of the book, your `master` branch has a broken structure (missing hyphen at the end of some code blocks). Until my fix branch is merged, there will be no full compilation of the book.

**Comment by Cpt-xx** [comment]
@jnavila I've incorporated almost all of your modifications (references [[_r_ and pointers to them should no longer exist as they don't exist in the English version either.. at least not in tag 2.1.75).

The build works, there is however an error for the README.asc where the level 0 should not exist according to my Idea asciidocter plugin. But that same error appears in the English version.

Could you double check and verify?

Thanks
