### ISSUE TITLE
How to get the corrections in?

### ISSUE THREAD

**Issue by Cpt-xx** [progit/progit2-nl#2]
Hi Scott,

I've got a starter question for you: I've made a lot of corrections and translated a few more chapters. Now I've got them pushed into the Cpt-xx/progit2 master and I thought I could create a pull request and point it to progit/progit2-nl. However, that doesn't fly, even though the SHA-1 is equal to the one of progit2-nl. How do I get the modifications in?
Do I:
- Fork the progit/progit2-nl, and drop the changes in (somehow... I'll have to figure that one out) locally and push them up to the new fork and then create a pull request from there
- Change the base ref of my local copy to progit/progit2-nl (not sure whether that would work correctly)
- Wait for your answer before I damage the progit/progit2-nl repo?

Thanks for your patience.

Cor

**Comment by schacon** [comment]
Sorry, I should have made this clearer. You should add the progit/progit2-nl repo as a new remote and push your branches there. Or delete your current fork and re-fork. Sadly there is no better way to do it.  Since you have write permissions on the progit/progit2-nl repo, opening them from there is probably better.

**Comment by Cpt-xx** [comment]
:+1:
